apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-back-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-back-user
  template:
    metadata:
      labels:
        app: micro-back-user
    spec:
      containers:
        - name: micro-back-user
          image: mywebapp.azurecr.io/pfa-micro-back-user:latest
          ports:
            - containerPort: 8093
