trigger:
- main  # ou une autre branche de votre choix

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '245aa7a1-b11c-404b-81e3-1ad91e319b15'
  containerRegistry: 'mywebapp.azurecr.io'
  IMAGE_TAG: '$(Build.BuildId)'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Images'
  steps:
  - task: AzureCLI@2
    inputs:
      containerRegistry: $(dockerRegistryServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Logging into ACR..."
        az acr login --name $(CONTAINER_REGISTRY)

        echo "Building and pushing Docker images..."
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Pipeline.Workspace)/docker-compose.yml'
      artifactName: 'docker-compose'
