# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: UseDocker@0
  displayName: 'Use Docker'
  inputs:
    command: 'login'
    containerRegistry: '$(dockerRegistryServiceConnection)'

- script: |
    docker-compose -f $(dockerComposeFile) build
  displayName: 'Build Docker images with Docker Compose'

- task: DockerCompose@0
  displayName: 'Push Docker Compose images'
  inputs:
    action: 'Push services'
    dockerComposeFile: '$(dockerComposeFile)'
    qualifyImageNames: true
    additionalImageTags: |
      $(Build.BuildId)
      latest