trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'da85116b-3ab2-405c-82ec-16dc0b6fd72e'
  containerRegistry: 'mywebapp.azurecr.io'
  dockerComposeFile: 'docker-compose.yml'

steps:
- task: DockerCompose@0
  displayName: 'Build Docker Compose Images'
  inputs:
    action: 'Build services'
    dockerComposeFile: '$(dockerComposeFile)'
    qualifyImageNames: true
    additionalImageTags: |
      $(Build.BuildId)
      latest
    containerregistry: '$(dockerRegistryServiceConnection:)'

- task: DockerCompose@0
  displayName: 'Push Docker Compose Images'
  inputs:
    action: 'Push services'
    dockerComposeFile: '$(dockerComposeFile)'
    qualifyImageNames: true
    additionalImageTags: |
      $(Build.BuildId)
      latest
    containerregistry: '$(dockerRegistryServiceConnection:)'
