trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'mywebapp'
  containerRegistry: 'mywebapp.azurecr.io'
  dockerComposeFile: 'docker-compose.yml'

steps:
  - task: DockerCompose@0
    displayName: 'Build Docker Compose Images'
    inputs:
      action: 'Build services'
      dockerComposeFile: '$(dockerComposeFile)'
      qualifyImageNames: true
      additionalImageTags: |
        $(Build.BuildId)
        latest
      containerregistry: '$(dockerRegistryServiceConnection:)'
  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: 'login'
      containerRegistry: '$(dockerRegistryServiceConnection)'

  - task: DockerCompose@0
    displayName: 'Push Docker Compose Images'
    inputs:
      action: 'Push services'
      dockerComposeFile: '$(dockerComposeFile)'
      qualifyImageNames: true
      additionalImageTags: |
        $(Build.BuildId)
        latest
      containerregistry: '$(dockerRegistryServiceConnection:)'
