trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'mywebapp'
  containerRegistry: 'mywebapp.azurecr.io'
  dockerComposeFile: 'docker-compose.yml'
  SONARQUBE_SERVICE_CONNECTION: 'bd-sonarcube'

jobs:
- job: SonarQubeAnalysis
  displayName: 'SonarQube Analysis for All Microservices'
  steps:

    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'bd-sonarcube'
        scannerMode: 'CLI'
        cliVersion: '0'
        configMode: 'manual'
        cliProjectKey: 'AT2Car_AT2Car_AZDfK74FKu-cI83U3IVc'
        cliProjectName: 'AT2Car'
        cliSources: '.'
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '20'
    - script: |
        for dir in micro-front-*/; do
          echo "Running SonarQube analysis for $dir"
          cd $dir
          npm install
          npm run build
          sonar-scanner -Dsonar.projectKey=$(basename $dir) -Dsonar.projectName=$(basename $dir) -Dsonar.sources=src -Dsonar.host.url=$(SONARQUBE_SERVICE_CONNECTION)
          cd ..
        done
      displayName: 'Run SonarQube Analysis for Frontend Microservices'

    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-voiture/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-favori/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-reservation/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-user/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-admin/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-api-gateway/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'micro-back-all/micro-back-discovery/pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

- job: DockerBuildAndPush
  displayName: 'Build and Push Docker Images'
  dependsOn: 
    - SonarQubeAnalysis
  steps:
    - task: DockerCompose@0
      displayName: 'Build Docker Compose Images'
      inputs:
        action: 'Build services'
        dockerComposeFile: '$(dockerComposeFile)'
        qualifyImageNames: true
        additionalImageTags: |
          $(Build.BuildId)
          latest
        containerregistry: '$(dockerRegistryServiceConnection)'
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: '$(dockerRegistryServiceConnection)'
    - task: DockerCompose@0
      displayName: 'Push Docker Compose Images'
      inputs:
        action: 'Push services'
        dockerComposeFile: '$(dockerComposeFile)'
        qualifyImageNames: true
        additionalImageTags: |
          $(Build.BuildId)
          latest
        containerregistry: '$(dockerRegistryServiceConnection)'
