trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'mywebapp'
  containerRegistry: 'mywebapp.azurecr.io'
  dockerComposeFile: 'docker-compose.yml'

stages:
- stage: Build
  jobs:
  - job: DockerBuildAndPush
    displayName: 'Build and Push Docker Images'
    steps:
      - task: DockerCompose@0
        displayName: 'Build Docker Compose Images'
        inputs:
          action: 'Build services'
          dockerComposeFile: '$(dockerComposeFile)'
          qualifyImageNames: true
          additionalImageTags: |
            $(Build.BuildId)
            latest
          containerregistry: '$(dockerRegistryServiceConnection)'
      - task: Docker@2
        displayName: 'Login to ACR'
        inputs:
          command: 'login'
          containerRegistry: '$(dockerRegistryServiceConnection)'
      - task: DockerCompose@0
        displayName: 'Push Docker Compose Images'
        inputs:
          action: 'Push services'
          dockerComposeFile: '$(dockerComposeFile)'
          qualifyImageNames: true
          additionalImageTags: |
            $(Build.BuildId)
            latest
          containerregistry: '$(dockerRegistryServiceConnection)'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    displayName: 'Deploy to AKS'
    steps:
      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'az-aymene'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az aks get-credentials --resource-group <your-resource-group> --name <your-aks-cluster>
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-api-gateway/deployment.yml
        displayName: 'Deploy micro-back-api-gateway'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-api-gateway/service.yml
        displayName: 'Expose micro-back-api-gateway'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-discovery/deployment.yml
        displayName: 'Deploy micro-back-discovery'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-discovery/service.yml
        displayName: 'Expose micro-back-discovery'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-favori/deployment.yml
        displayName: 'Deploy micro-back-favori'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-favori/service.yml
        displayName: 'Expose micro-back-favori'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-reservation/deployment.yml
        displayName: 'Deploy micro-back-reservation'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-reservation/service.yml
        displayName: 'Expose micro-back-reservation'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-user/deployment.yml
        displayName: 'Deploy micro-back-user'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-user/service.yml
        displayName: 'Expose micro-back-user'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-voiture/deployment.yml
        displayName: 'Deploy micro-back-voiture'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-back-all/micro-back-voiture/service.yml
        displayName: 'Expose micro-back-voiture'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-front-admin/deployment.yml
        displayName: 'Deploy micro-front-admin'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-front-admin/service.yml
        displayName: 'Expose micro-front-admin'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-front-visiteur/deployment.yml
        displayName: 'Deploy micro-front-visiteur'
      - script: kubectl apply -f $(Build.SourcesDirectory)/pfa/micro-front-visiteur/service.yml
        displayName: 'Expose micro-front-visiteur'
