trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '245aa7a1-b11c-404b-81e3-1ad91e319b15'
  containerRegistry: 'mywebapp.azurecr.io'
  tag: '$(Build.BuildId)'
  dockerComposeFile: 'docker-compose.yml'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Login to Azure Container Registry
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)

    - script: |
        docker-compose -f $(dockerComposeFile) build
      displayName: Build Docker images with Docker Compose

    - script: |
        docker-compose -f $(dockerComposeFile) push
      displayName: Push Docker images to Azure Container Registry
