apiVersion: v1
kind: Service
metadata:
  name: micro-back-reservation
spec:
  selector:
    app: micro-back-reservation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092
  type: LoadBalancer
