apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-back-discovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-back-discovery
  template:
    metadata:
      labels:
        app: micro-back-discovery
    spec:
      containers:
        - name: micro-back-discovery
          image: mywebapp.azurecr.io/pfa-micro-back-discovery:latest
          ports:
            - containerPort: 8762
