apiVersion: v1
kind: Service
metadata:
  name: micro-back-discovery
spec:
  selector:
    app: micro-back-discovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8762
  type: LoadBalancer
