apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-back-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micro-back-admin
  template:
    metadata:
      labels:
        app: micro-back-admin
    spec:
      containers:
        - name: micro-back-admin
          image: mywebapp.azurecr.io/pfa-micro-back-admin:latest
          ports:
            - containerPort: 8096
