apiVersion: v1
kind: Service
metadata:
  name: micro-back-voiture
spec:
  selector:
    app: micro-back-voiture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8095
  type: LoadBalancer
